// Anonymous app-start telemetry: owns the opt-out check, the Aptabase wire
// contract and the one outbound POST. That is the whole of this module's
// territory.
//
// It must NOT know routes, the board payload, project paths, flowcharge/
// content, the project registry, or how the data directory was resolved — the
// caller supplies dataDir. The persisted ID file belongs to
// src/lib/telemetry-install-id.ts.
//
// The opt-out variable is read inside isTelemetryEnabled and never at module
// scope: the entry generated by tools/package-cli.mjs imports this module
// statically, and a module-scope read would hoist above the applyCliDefaults
// call, for the reason tools/package-cli.mjs:122-130 records.

import { readOrCreateInstallId } from './telemetry-install-id.js';

// Aptabase's ingestion endpoint for a single event. A constant, and no exported
// function takes a destination argument, so no caller can steer where this
// module reaches — the same rule src/lib/update-check.ts:43-47 follows.
export const APTABASE_EVENT_URL: string = 'https://us.aptabase.com/api/v0/event';

// Aptabase's public client identifier, not a secret. Compiling it into the
// binary is correct and adds no credential to the shipped artefact.
export const APTABASE_APP_KEY: string = 'A-US-2875955020';

export const TELEMETRY_OPT_OUT_VAR: string = 'FLOWCHARGE_NO_TELEMETRY';

const DEFAULT_TIMEOUT_MS = 3000;

// Aptabase's own ceiling on the sdkVersion field.
const SDK_VERSION_MAX = 40;

export interface TelemetryInput {
  dataDir: string; // where .praxis-telemetry.json lives
  appVersion: string; // PRAXIS_APP_VERSION, always non-empty by this point
  platform: string; // process.platform
  osRelease: string; // os.release()
  env: NodeJS.ProcessEnv; // read for the opt-out variable only
}

export interface AptabaseEvent {
  timestamp: string; // ISO 8601, from new Date().toISOString()
  sessionId: string; // decimal digits, 18 characters
  eventName: string; // 'app_started'
  systemProps: {
    isDebug: boolean; // always false
    osName: string; // 'macOS' | 'Linux' | 'Windows' | the raw platform
    osVersion: string; // os.release()
    appVersion: string;
    sdkVersion: string; // `flowcharge-cli@${appVersion}`, cut to 40 characters
  };
  props: { installId: string };
}

// Telemetry is on when the variable is unset, '' or '0', and off for any other
// value. The variable is read here, inside the function, and nowhere else.
export function isTelemetryEnabled(env: NodeJS.ProcessEnv): boolean {
  const raw = env[TELEMETRY_OPT_OUT_VAR];
  if (raw === undefined) return true;
  return raw === '' || raw === '0';
}

// Any platform string this repository does not name is passed through unchanged
// rather than reported as 'Unknown', so a new platform still counts as itself.
export function osNameFor(platform: string): string {
  if (platform === 'darwin') return 'macOS';
  if (platform === 'linux') return 'Linux';
  if (platform === 'win32') return 'Windows';
  return platform;
}

// Eighteen decimal digits: the epoch seconds followed by random8 padded to
// eight. Built by string concatenation on purpose — arithmetic is wrong here,
// because epochSeconds * 1e8 is about 1.8e17, past Number.MAX_SAFE_INTEGER, and
// would silently lose the low digits. Aptabase reads the first ten digits back
// as the session's start time.
export function newSessionId(nowMs: number, random8: number): string {
  const epochSeconds = Math.floor(nowMs / 1000);
  return `${epochSeconds}${String(random8).padStart(8, '0')}`;
}

export function buildAppStartedEvent(
  input: TelemetryInput,
  installId: string,
  sessionId: string,
  timestamp: string,
): AptabaseEvent {
  return {
    timestamp,
    sessionId,
    eventName: 'app_started',
    systemProps: {
      isDebug: false,
      osName: osNameFor(input.platform),
      osVersion: input.osRelease,
      appVersion: input.appVersion,
      sdkVersion: `flowcharge-cli@${input.appVersion}`.slice(0, SDK_VERSION_MAX),
    },
    props: { installId },
  };
}

// Resolves and never rejects, on every path. The whole body sits inside one
// unconditional catch, for the reason src/lib/update-check.ts:119-125 records:
// AbortSignal.timeout rejects with a TimeoutError DOMException rather than a
// plain Error, so an instanceof-filtered catch would let it escape. It logs
// nothing on any path, success included, so the Aptabase dashboard and the ID
// file are the only observable signals.
export async function trackAppStarted(
  input: TelemetryInput,
  timeoutMs: number = DEFAULT_TIMEOUT_MS,
): Promise<void> {
  try {
    // Before the filesystem and before the network: an opted-out run writes no
    // file and makes no request.
    if (!isTelemetryEnabled(input.env)) return;

    const { installId } = readOrCreateInstallId(input.dataDir);
    const sessionId = newSessionId(Date.now(), Math.floor(Math.random() * 1e8));
    const event = buildAppStartedEvent(input, installId, sessionId, new Date().toISOString());

    // No cookie and no credential. The response body is ignored entirely —
    // there is nothing for a caller to do with it.
    await fetch(APTABASE_EVENT_URL, {
      method: 'POST',
      headers: {
        'App-Key': APTABASE_APP_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(event),
      signal: AbortSignal.timeout(timeoutMs),
    });
  } catch {
    // Every failure mode of this feature is "do nothing".
  }
}
