// The CLI entry point's bootstrap step, typed. It compiles to
// dist/cli-bootstrap.js, which is the exact path the entry generated by
// tools/package-cli.mjs imports, so this file sits at src/ rather than under
// src/lib/ or src/http/.
//
// It knows the two environment variables the packaged binary must have in place
// before dist/server.js is imported, and the directory they resolve to. It
// knows nothing about routes, the board payload, flowcharge/ parsing or Bun.
import fs from 'node:fs';
import path from 'node:path';
import type { CliBootstrapInput, CliBootstrapResult } from './ports/cli-bootstrap.js';

// Both defaults are explicit emptiness tests, not ??=: an environment variable
// set to '' is '', not undefined, and an explicit value must still win.
export function applyCliDefaults(input: CliBootstrapInput): CliBootstrapResult {
  const { version, homeDir, env } = input;

  if (!env.PRAXIS_APP_VERSION) env.PRAXIS_APP_VERSION = version;

  if (!env.PRAXIS_DATA_DIR) env.PRAXIS_DATA_DIR = path.join(homeDir, '.flowcharge');
  const dataDir = env.PRAXIS_DATA_DIR;

  // Recursive, and on the resolved directory whichever of the two sources it
  // came from. A packaged Bun executable resolves __dirname inside the
  // read-only /$bunfs, so this directory is the only writable place the app has.
  fs.mkdirSync(dataDir, { recursive: true });

  return { dataDir };
}
